-- CreateTable
CREATE TABLE `loads` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `serial` INTEGER NOT NULL,
    `timestamp` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `status` VARCHAR(191) NOT NULL DEFAULT 'CONFIRMED',
    `vehicleNumber` VARCHAR(191) NOT NULL,
    `driverName` VARCHAR(191) NULL,
    `brokerDetails` VARCHAR(191) NOT NULL,
    `loadingDate` VARCHAR(191) NOT NULL,
    `loadingLocation` VARCHAR(191) NOT NULL,
    `unloadingDate` VARCHAR(191) NOT NULL,
    `unloadingLocation` VARCHAR(191) NOT NULL,
    `sku` VARCHAR(191) NOT NULL,
    `tonnage` DOUBLE NOT NULL,
    `perTonPrice` DOUBLE NOT NULL,
    `km` DOUBLE NOT NULL,
    `externalPointMillKm` DOUBLE NOT NULL,
    `brokerCommission` DOUBLE NOT NULL DEFAULT 0,
    `loadingCost` DOUBLE NOT NULL DEFAULT 0,
    `unloadingCost` DOUBLE NOT NULL DEFAULT 0,
    `rto` DOUBLE NOT NULL DEFAULT 0,
    `fastagCost` DOUBLE NOT NULL DEFAULT 0,
    `totalKm` DOUBLE NOT NULL,
    `litres` DOUBLE NOT NULL,
    `fuelCost` DOUBLE NOT NULL,
    `driver` DOUBLE NOT NULL,
    `projectedExpenses` DOUBLE NOT NULL,
    `perKmCost` DOUBLE NOT NULL,
    `marginPerTrip` DOUBLE NOT NULL,
    `finalAmount` DOUBLE NOT NULL,
    `brokerTripCost` DOUBLE NOT NULL,
    `netMargin` DOUBLE NOT NULL,
    `baseClosingRate` DOUBLE NOT NULL,
    `totalQuotation` DOUBLE NOT NULL,
    `quotationPerTon` DOUBLE NOT NULL,
    `tripAmount` DOUBLE NOT NULL DEFAULT 0,
    `rateVersion` VARCHAR(191) NOT NULL DEFAULT 'v1',
    `tripMargin` DOUBLE NOT NULL DEFAULT 0,

    PRIMARY KEY (`id` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

